version: '3.8'

services:
  database:
    image: postgres
    ports:
      - "5432:5432" 
    restart: always
    env_file: .env
  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080