services:
  database:
    image: postgres
    ports:
      - "5432:5432" 
    restart: always
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080
  app:
      build:
        context: .
        dockerfile: Dockerfile
      env_file: .env
      environment:
        POSTGRES_HOST: database
      ports:
        - "8000:8000"
      depends_on:
        database:
          condition: service_healthy